# Configuration for the GitLab CI.

# Go tests, on various Go versions.
.golang_template: &golang
  stage: test
  script:
    - go test ./...
    - go test -race ./...

golang_1.11:
  <<: *golang
  image: golang:1.11  # Oldest supported version (for now).

golang_latest:
  <<: *golang
  image: golang:latest

coverage:
  <<: *golang
  image: golang:latest
  script:
    - go test -covermode=count -coverprofile=coverage.out
    - go get github.com/mattn/goveralls
    - goveralls -coverprofile=coverage.out -service=gitlab -repotoken=$COVERALLS_TOKEN

