# Configuration for https://travis-ci.org/

language: go
dist: trusty
sudo: false

go_import_path: blitiri.com.ar/go/spf

go:
    - 1.7
    - stable
    - master

before_install:
    - go get github.com/mattn/goveralls

script:
    - go test ./...
    - go test -race ./...
    - go test -v -covermode=count -coverprofile=coverage.out
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
